### ISSUE TITLE
テキストボックスでことえりがアクティブにならない

### ISSUE THREAD

**Issue by kenji-namba** [codic-project/codic-intellij-plugin#1]
Cmd+Shift+Dでポップアップ上の検索テキストボックスにフォーカスが移った際、かなキーを押しても日本語入力モードにならない。ただし、ポップアップの別の部分をクリックしてフォーカスを与えると入力モードを切り替えれる。

他の環境（Windowsなど) でも同様の現象が起きるようでしたら、ご報告ください。

_環境_
Mac 10.8.5
ことえり
PHPStorm 8.0.3 / IntelliJ IDEA13.1.5

**Comment by axshia** [comment]
Google日本語入力でも同様の現象が起きているので報告します。

環境
Mac 10.11.1
Google日本語入力
PHPStorm 10.0.1

**Comment by kenji-namba** [comment]
ポップアップを、ダイアログベースに変更しました。1.04でこの問題は修正済みです。
