### ISSUE TITLE
同社製のものへの対応の要求

### ISSUE THREAD

**Issue by anatawa12** [codic-project/codic-intellij-plugin#11]
Rider EAPに対応させてもらえませんか？
お願いします

**Comment by kenji-namba** [comment]
@anatawa12 さん
Rider EAPへの対応 検討してみます。
ちなみに、↓のjarを「install plugin form disk」で指定してもダメでしょうか。
https://github.com/codic-project/codic-intellij-plugin/blob/master/codic-intellij-plugin.jar

**Comment by anatawa12** [comment]
ごめんなさい。できました。
公式の方で登録してもらえますでしょうか?
(探しやすくするため)

**Comment by kenji-namba** [comment]
@anatawa12 さん
公式を更新しています。
ご報告ありがとうございました。
