### ISSUE TITLE
IntelliJ 2020.1への対応

### ISSUE THREAD

**Issue by naoyukik** [codic-project/codic-intellij-plugin#13]
プラグインを IntelliJ(ファミリー) 2020 に対応していただけないでしょうか？
何卒よろしくお願いいたします。

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。バージョン1.1.0 にて IntelliJ Platform 2020.1 に対応しています。IDEからアップデートしてください。

**Comment by naoyukik** [comment]
ご対応ありがとうございました！
