### ISSUE TITLE
文字列をアルファベットに変換後、置換できない時がある

### ISSUE THREAD

**Issue by axshia** [codic-project/codic-intellij-plugin#2]
入力した関数名を選択して「Cmd+Shift+D」でポップアップを立ち上げ、
候補をダブルクリックや十字キーで選択してEnterしても置換されずに
日本語のままになる時があります。

![2015-11-18 13 39 50](https://cloud.githubusercontent.com/assets/998200/11232857/ae78adde-8dfa-11e5-9f03-b02a316e5d55.png)

一度なると、別ファイルでも再起動するまで直りません。

また連続で失敗していて、別ファイルに切り替えて作業していると
気づかないうちに連続で置換されている事があります。

![2015-11-18 13 45 22](https://cloud.githubusercontent.com/assets/998200/11232853/a556b782-8dfa-11e5-918c-95ecada336c8.png)

再現手順が不明確なので、明確に判明したらコミットします。

> 環境
> Mac 10.11.1
> Google日本語入力
> PHPStorm 10.0.1

**Comment by axshia** [comment]
再現手順が取れたので報告します。

1,phpstorm起動

2,ファイルAで「Cmd+Shift+D」で日本語を置換します

![2015-11-18 13 56 25](https://cloud.githubusercontent.com/assets/998200/11232998/5d8b3bce-8dfc-11e5-9b84-b898ac6e0f05.png)
↓
![2015-11-18 13 56 34](https://cloud.githubusercontent.com/assets/998200/11233003/642ffa46-8dfc-11e5-8e0e-f091b9281688.png)
置換できる

3,ファイルBで「Cmd+Shift+D」で日本語を置換します

![2015-11-18 13 57 11](https://cloud.githubusercontent.com/assets/998200/11233018/7b003506-8dfc-11e5-82d4-51a4c7290648.png)
↓
![2015-11-18 13 57 17](https://cloud.githubusercontent.com/assets/998200/11233020/8118874a-8dfc-11e5-943f-2e2a744710da.png)
↓
![2015-11-18 13 57 25](https://cloud.githubusercontent.com/assets/998200/11233022/86f67dde-8dfc-11e5-9f4a-b9b856d091c4.png)
置換できずに日本語のまま

4,Aに戻ると、置換できなかったアルファベットが追記されている。

![2015-11-18 13 57 33](https://cloud.githubusercontent.com/assets/998200/11233025/8d1f43d0-8dfc-11e5-8afd-20c4dda130f8.png)

**Comment by kenji-namba** [comment]
報告ありがとうございました。
1.0.3にて修正を行っておりますので、リリース承認されましたら IDEの環境設定より更新してください。

**Comment by axshia** [comment]
対応ありがとうございます。
プラグイン更新後、私の環境では正常に動作しました。
