### ISSUE TITLE
記法ドロップダウンがポップアップの裏側に潜る

### ISSUE THREAD

**Issue by nyamairi** [codic-project/codic-intellij-plugin#3]
Cmd+Shift+Dで表示されたポップアップの記法ドロップダウンをクリックするとポップアップの裏側に潜ってしまって要素を選択できない。

環境
Mac 10.11.1
IntelliJ IDEA 15.0.1
(Google日本語入力)

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。
以下、手持ちの環境では再現しませんでしたので、
IDEA を15にアップグレードして再現を試みてみます。

環境 : Mac 10.8 / IntelliJ IDEA 13
![2015-12-05 14 57 49](https://cloud.githubusercontent.com/assets/960571/11606328/92f6375c-9b60-11e5-86c8-dc04cd484090.png)

**Comment by tasuku-s** [comment]
僕のところでも同様の不具合に遭遇しました

環境は Mac 10.10.5 / Intellij IDEA 15.0.1
Google 日本語入力 2.17.2300.1

無関係かもしれませんが、ディスプレイが3枚あります

![image](https://cloud.githubusercontent.com/assets/8175563/11775747/c2f99f86-a284-11e5-8ccc-bb36a938c1c5.png)

**Comment by kenji-namba** [comment]
nyamairiさん
Ver. 1.0.4でポップアップをダイアログベースに変更しています。表題の問題が、1.0.4でも発生するか確認していただけないでしょうか。

**Comment by nyamairi** [comment]
@kenji-namba 確認したところ問題なくドロップダウンが表示されました:)
![2015-12-24 10 13 33](https://cloud.githubusercontent.com/assets/997726/11987691/24e7da6a-aa27-11e5-9b12-a6289314cd88.png)

ご対応いただきありがとうございます。
