### ISSUE TITLE
ポップアップ内で日本語入力が有効化できない

### ISSUE THREAD

**Issue by tasuku-s** [codic-project/codic-intellij-plugin#5]
Cmd+Shift+D でポップアップを表示した直後、日本語入力ができませんでした

ただ、一度ポップアップをクリックすると日本語入力できるようにりました (変換表が裏に回ってしまいますが)

![image](https://cloud.githubusercontent.com/assets/8175563/11775850/be00ffc8-a285-11e5-82ea-873d469039e5.png)

無関係かもしれませんが、IntelliJからポップアップ側にウィンドウのフォーカスが移動していないのが問題のような気がします

環境は Mac 10.10.5 / Intellij IDEA 15.0.1
Google 日本語入力 2.17.2300.1

です

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。
おっしゃる通り、IME（ことえり、Google日本語入力）がアクティブウィンドウのフォーカスコントロールにしか有効化しない問題のような気がしていますが、今のところスマートな解決策は見つかっていません。Popupを止めてDialogにする方法など検討していますので、もう少しお待ちください。

現象としては、こちらのバグと同じですので、このIssueはクローズし、#1で追跡します。
https://github.com/codic-project/codic-intellij-plugin/issues/1
