### ISSUE TITLE
候補が多い場合に見えない項目がある

### ISSUE THREAD

**Issue by tasuku-s** [codic-project/codic-intellij-plugin#6]
お世話になっております

候補が5件より多い場合に、カーソルは移動できるがスクロールしないので裏に隠れてしまって見えない状態になってしまっているようです

![image](https://cloud.githubusercontent.com/assets/8175563/11989509/56e13f14-aa42-11e5-832b-b6f402f729da.png)

**Comment by kenji-namba** [comment]
報告ありがとうございます。
ver. 1.0.5でスクロールバーを付けましたので、IDEよりアップデートしてください。

**Comment by tasuku-s** [comment]
早速のご対応ありがとうございます。
スクロールできるようになったのを確認いたしました。
