### ISSUE TITLE
IntelliJ IDEA 2016.1以降設定ダイアログが表示されない

### ISSUE THREAD

**Issue by ghost** [codic-project/codic-intellij-plugin#9]
IntelliJ IDEA 15までは普通に使えていたのですが、バージョンアップしたら使えなくなりました。
プラグインの再インストールを行っても設定項目が見つかりません。

以下環境です。

IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_45-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by kenji-namba** [comment]
ご報告ありがとうございました。
Version 1.0.11 で問題は解決していますので、
IntelliJ 2016.1 関連の製品のお使いの方は、1.0.11 へアップデートしてください。

**Comment by ghost** [comment]
ありがとうございます。
アップデート後項目が出てきて動くことを確認できました。
